[package]
name = "imspectro"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
realfft = "3.0.0"
image = "0.24.2"
byteorder = "1.4.3"